### ISSUE TITLE
Error php 

### ISSUE THREAD

**Issue by jbtele29** [invisiblemarcel/glpiwithbookstack#2]
Hello, 

Thanks for plugin but I have this errors
[2024-05-24 17:20:08] glpiphplog.WARNING:   *** PHP Warning (2): Trying to access array offset on value of type bool in /var/www/html/glpi/plugins/glpiwithbookstack/inc/integrate.class.php at line 17
  Backtrace :
  src/CommonGLPI.php:383                             PluginGlpiwithbookstackIntegrate->getTabNameForItem()
  src/CommonGLPI.php:342                             CommonGLPI->addStandardTab()
  src/CommonGLPI.php:893                             CommonGLPI->defineAllTabs()
  src/CommonGLPI.php:1230                            CommonGLPI->showTabsContent()
  src/CommonDBTM.php:6566                            CommonGLPI->display()
  front/ticket.form.php:265                          CommonDBTM::displayFullPageForItem()
  public/index.php:82                                require()

[2024-05-24 17:20:08] glpiphplog.WARNING:   *** PHP Warning (2): Trying to access array offset on value of type bool in /var/www/html/glpi/plugins/glpiwithbookstack/inc/integrate.class.php at line 160
  Backtrace :
  src/CommonGLPI.php:694                             PluginGlpiwithbookstackIntegrate::displayTabContentForItem()
  ajax/common.tabs.php:120                           CommonGLPI::displayStandardTab()
  public/index.php:82                                require()

I use GLPI 10.0.15 and Bookstack  v24.02.2  in french
In config for url its https://example.com/api/books or https://example.com

Thanks

**Comment by jbtele29** [comment]
Update : 
I got curl to work by disabling SSL certificate verification with 
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

$ch = curl_init($url_api);
curl_setopt($ch, CURLOPT_HTTPGET, true);
// set timeout for curl to prevent long time loading if Bookstack instance is not reachable
**_curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);_**
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $my_config['curl_timeout']);

Nowx i have this error
`[2024-05-24 18:22:36] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "total" in /var/www/html/glpi/plugins/glpiwithbookstack/inc/integrate.class.php at line 122
  Backtrace :
  ...ns/glpiwithbookstack/inc/integrate.class.php:15 PluginGlpiwithbookstackIntegrate->getBookstackSearchResults()
  src/CommonGLPI.php:383                             PluginGlpiwithbookstackIntegrate->getTabNameForItem()
  src/CommonGLPI.php:342                             CommonGLPI->addStandardTab()
  src/CommonGLPI.php:893                             CommonGLPI->defineAllTabs()
  src/CommonGLPI.php:1230                            CommonGLPI->showTabsContent()
  src/CommonDBTM.php:6566                            CommonGLPI->display()
  front/ticket.form.php:265                          CommonDBTM::displayFullPageForItem()
  public/index.php:82                                require()

[2024-05-24 18:22:36] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "total" in /var/www/html/glpi/plugins/glpiwithbookstack/inc/integrate.class.php at line 125
  Backtrace :
  ...ns/glpiwithbookstack/inc/integrate.class.php:15 PluginGlpiwithbookstackIntegrate->getBookstackSearchResults()
  src/CommonGLPI.php:383                             PluginGlpiwithbookstackIntegrate->getTabNameForItem()
  src/CommonGLPI.php:342                             CommonGLPI->addStandardTab()
  src/CommonGLPI.php:893                             CommonGLPI->defineAllTabs()
  src/CommonGLPI.php:1230                            CommonGLPI->showTabsContent()
  src/CommonDBTM.php:6566                            CommonGLPI->display()
  front/ticket.form.php:265                          CommonDBTM::displayFullPageForItem()
  public/index.php:82                                require()

[2024-05-24 18:22:36] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "data" in /var/www/html/glpi/plugins/glpiwithbookstack/inc/integrate.class.php at line 134
  Backtrace :
  ...ns/glpiwithbookstack/inc/integrate.class.php:15 PluginGlpiwithbookstackIntegrate->getBookstackSearchResults()
  src/CommonGLPI.php:383                             PluginGlpiwithbookstackIntegrate->getTabNameForItem()
  src/CommonGLPI.php:342                             CommonGLPI->addStandardTab()
  src/CommonGLPI.php:893                             CommonGLPI->defineAllTabs()
  src/CommonGLPI.php:1230                            CommonGLPI->showTabsContent()
  src/CommonDBTM.php:6566                            CommonGLPI->display()
  front/ticket.form.php:265                          CommonDBTM::displayFullPageForItem()
  public/index.php:82                                require()

[2024-05-24 18:22:36] glpiphplog.WARNING:   *** PHP Warning (2): foreach() argument must be of type array|object, null given in /var/www/html/glpi/plugins/glpiwithbookstack/inc/integrate.class.php at line 134
  Backtrace :
  ...ns/glpiwithbookstack/inc/integrate.class.php:15 PluginGlpiwithbookstackIntegrate->getBookstackSearchResults()
  src/CommonGLPI.php:383                             PluginGlpiwithbookstackIntegrate->getTabNameForItem()
  src/CommonGLPI.php:342                             CommonGLPI->addStandardTab()
  src/CommonGLPI.php:893                             CommonGLPI->defineAllTabs()
  src/CommonGLPI.php:1230                            CommonGLPI->showTabsContent()
  src/CommonDBTM.php:6566                            CommonGLPI->display()
  front/ticket.form.php:265                          CommonDBTM::displayFullPageForItem()
  public/index.php:82                                require()

[2024-05-24 18:22:36] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "total" in /var/www/html/glpi/plugins/glpiwithbookstack/inc/integrate.class.php at line 142
  Backtrace :
  ...ns/glpiwithbookstack/inc/integrate.class.php:15 PluginGlpiwithbookstackIntegrate->getBookstackSearchResults()
  src/CommonGLPI.php:383                             PluginGlpiwithbookstackIntegrate->getTabNameForItem()
  src/CommonGLPI.php:342                             CommonGLPI->addStandardTab()
  src/CommonGLPI.php:893                             CommonGLPI->defineAllTabs()
  src/CommonGLPI.php:1230                            CommonGLPI->showTabsContent()
  src/CommonDBTM.php:6566                            CommonGLPI->display()
  front/ticket.form.php:265                          CommonDBTM::displayFullPageForItem()
  public/index.php:82                                require()
`

Is it possible to search with the ticket title only as I don't use categories and tags?
Thanks

**Comment by invisiblemarcel** [comment]
> Hello,
> 
> Thanks for plugin but I have this errors [2024-05-24 17:20:08] glpiphplog.WARNING: *** PHP Warning (2): Trying to access array offset on value of type bool in /var/www/html/glpi/plugins/glpiwithbookstack/inc/integrate.class.php at line 17 Backtrace : src/CommonGLPI.php:383 PluginGlpiwithbookstackIntegrate->getTabNameForItem() src/CommonGLPI.php:342 CommonGLPI->addStandardTab() src/CommonGLPI.php:893 CommonGLPI->defineAllTabs() src/CommonGLPI.php:1230 CommonGLPI->showTabsContent() src/CommonDBTM.php:6566 CommonGLPI->display() front/ticket.form.php:265 CommonDBTM::displayFullPageForItem() public/index.php:82 require()
> 
> [2024-05-24 17:20:08] glpiphplog.WARNING: *** PHP Warning (2): Trying to access array offset on value of type bool in /var/www/html/glpi/plugins/glpiwithbookstack/inc/integrate.class.php at line 160 Backtrace : src/CommonGLPI.php:694 PluginGlpiwithbookstackIntegrate::displayTabContentForItem() ajax/common.tabs.php:120 CommonGLPI::displayStandardTab() public/index.php:82 require()
> 
> I use GLPI 10.0.15 and Bookstack v24.02.2 in french In config for url its https://example.com/api/books or https://example.com
> 
> Thanks

Hey,

thanks for the error codes.
Well i just setup a quick test environment.
I used a fresh install of glpi with the latest version of my plugin.
The Bookstack instance is my own which is accessible through a valid Let's Encrypt certificate.
So I guess you maybe use Bookstack on HTTPS with a self signed or outdated or broken certificate?

In the settings it's important that you just set Bookstack's base url. Do not append /api or something.
For my instance I created a extra user with API permission and API-Token.

It should look like:
![grafik](https://github.com/invisiblemarcel/glpiwithbookstack/assets/66548244/7b5d83a8-b4ce-40b6-961a-1192779b8714)

Can you check these steps please?

**Comment by jbtele29** [comment]
Hello, 
I use a certificat SSL in local with a specific certificate authority (CA)
For my settings : 
I have a user api on bookstack and url is good now 
![image](https://github.com/invisiblemarcel/glpiwithbookstack/assets/139154287/006c035b-7fb2-4288-97e6-b692bbf94fea)
Thanks

**Comment by invisiblemarcel** [comment]
That sounds good. So your problem is solved now and the API is delivering fine in the ticket form?
Then I would maybe just add a check and a description later so this problem won't happen to the next user.

**Comment by jbtele29** [comment]
Hello, 

Yes with `curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);` it's work
A check to disable SSL verification if it's possible.
Thanks

**Comment by invisiblemarcel** [comment]
I just added the option for disable SSL_VERIFYPEER and put a description under the base URL so it's easier to understand which part of the URL you need to put in.
See commit b1ba2467b35d7969284dc68150f5136024ea04f5
