### ISSUE TITLE
Bookstack integration with GLPI only works with a slash (/) at the end

### ISSUE THREAD

**Issue by pedroalves5770** [invisiblemarcel/glpiwithbookstack#4]
I know it's counterintuitive and exactly the opposite of what the field help suggests, but if I leave the URL without a trailing slash, the integration doesn't work. And if I add a slash at the end of the URL, the integration works, but the redirection and search are performed with double slashes, resulting in no results being returned.

1.1) This is how is set up without the slash
![Imagem do WhatsApp de 2024-10-16 à(s) 08 33 10_7c46d215](https://github.com/user-attachments/assets/c2e54666-a1ca-4e6c-8564-ef5e5c61daa3)

1.2) With this config, my ticket page doesn't sync with Bookstack
![Imagem do WhatsApp de 2024-10-16 à(s) 08 33 48_8a74945c](https://github.com/user-attachments/assets/09efbc0d-023e-4c84-9ebc-afb4cad1628e)

2.1) This is how is set up with the slash
![Imagem do WhatsApp de 2024-10-16 à(s) 08 31 27_6c08a994](https://github.com/user-attachments/assets/713484b5-7149-42ba-b079-49b6af47e35b)

2.2) I finally get to see the integration 
![Imagem do WhatsApp de 2024-10-16 à(s) 08 32 17_2ee18592](https://github.com/user-attachments/assets/eb904460-c5e2-4aae-89a3-dba5ac30ac5b)

2.3) But in this case, the URL gets two slashes and the search doesn't work 
![Imagem do WhatsApp de 2024-10-16 à(s) 08 36 02_c81a3ea3](https://github.com/user-attachments/assets/bf82e09a-7183-427e-8a7e-d7ad4fa33902)

2.4) If I manually remove the slash, it gets the page correctly 
![Imagem do WhatsApp de 2024-10-16 à(s) 08 39 27_63909b6f](https://github.com/user-attachments/assets/1a0c67ff-b1a7-42fb-ab6c-1df4e2fcf8f7)

My bookstack was configured with docker compose file, and the line that I think has a job in this is the one below:

      - APP_URL="http://192.168.10.13"

This is how I set up, I tried with slash at the end, with no success.
I know this is not the best way to set up all the environment, but my company doesn't offer much support, and we try our best to test new solutions with our own machines and suggest new software at the company.

**Comment by pedroalves5770** [comment]
Found a solution!

Just added the code below on the /etc/nginx/nginx.conf file

```
location / {
    rewrite ^//(.*) /$1 permanent;^
}
```

**Comment by invisiblemarcel** [comment]
@pedroalves5770 
Hi Pedro,

thanks for sharing your problem and especially your solution here.

I use Traefik as a reverse Proxy so maybe that reverse proxy handles the traffic different.

Let me add something. GLPI connects with the PHP backend directly to Bookstack. So you can connect these 2 tools within a docker network. There is no client side connection to Bookstack. In that case you would not need to pass any reverse proxy that might be between the tools and you do not leave internal docker network. That will also improve speed and security.
